import { Bebas_Neue, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Nav from "./components/common-components/Nav";
import Footer from "./components/common-components/Footer";
import AosWrapper from "./components/common-components/AosWrapper";
import BackToTop from "./components/common-components/BackToTop";
import CustomCursor from "./components/common-components/CustomCursor";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./providers/AuthProvider";
import { CartProvider } from "./providers/CartProvider";

const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
});

export const metadata = {
  title: "fashion",
  description: "Generated by shimanto.dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${jakarta.variable} antialiased font-jakarta`}
      >
        <Toaster position="top-center" reverseOrder={false} />
        <AuthProvider>
          <CartProvider>
            <CustomCursor />
            <BackToTop />
            <Nav />
            <AosWrapper>{children}</AosWrapper>
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
